language: node_js
node_js: 9
env:
  global:
  - GITHUB_REPO: bitshareseurope/paperwallet.bitshares.eu
  - CXX: g++-4.8
  - secure: KwNgdVqoXRlD3C1PtyrP/Fl9WDWkeBu9cNYKXTW7L6tnaWQOjFTd9/tKowyeYgPzIV63ucYgGR72lE/PWtdISDh1l49xDaKmkVdvxQRDvJSvrbbvqFzdqS5gQfLaCKRVQu3YFLVrqfwYQEJ1Vt5upo59MuRmFlJSFd6XEa44l+o/V25HFkpEyVmcVnDmr+T5adaDSMZoX+QCdPIezPVBRdlkqJhHLxOj6Ym8d5DyXb1nP3It4zwS6cXhgBnTSn+JOnE1r1WdZgls8iVDKxAB9HA1cJfs/wGTv59MXwJbwShEQWWpE4YdV4BJ5SUZgDMU89wkaoXUlFBKHXPBeg6HB/26yRer7nOqPkTUNB7dTdH+/urR+ujHWonQpBR6Q6VMgkqFG/vMP9EpeYIy6nB58Jl8IkcxZAPDM7bg33eIemh3W2EyKmYlG6s9EzIRmrryKqeSrwUVFI/p8s4F/SdEjWZy1SPj1+C6eFtTZq9RnhP+J/4CbxHEInC/hDweIRnG44/CZl9yda2wKMGiyUOvk1evHvKiG2PnAE5j5X36nsR+z7AGkRdBeK+hZQjdMcSeyzVB6gXw91L6C4l6WXF65LOo9k/ZdX4H4h1mEz9/Kx9QR95wMiASwarK9QXTeKW+6Mo9jkJJt0lVpebAW6LXJAp4BMCN8uinia5WeTxqllo=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
  - node_modules
install:
- npm i
script:
- npm run build
notifications:
  email: false
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: "$GITHUB_TOKEN"
  repo: "$GITHUB_REPO"
  keep-history: true
  on:
    branch: master
